commonLabels:
- path: metadata/labels
  create: true
- path: spec/selector
  create: true
  kind: Service
- path: spec/selector/matchLabels
  create: true
  kind: StatefulSet
- path: spec/template/metadata/labels
  create: true
  kind: StatefulSet
